version: '2'
services:

  nginx:
      image: nginx
      volumes:
        - .:/usr/share/nginx/html
        - ./default.conf:/etc/nginx/conf.d/default.conf
      restart: always
      ports:
        - "8088:80"